trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  VENV_DIR: 'venv'

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'

- script: |
    python -m venv $(VENV_DIR)
    source $(VENV_DIR)/bin/activate
    pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    source $(VENV_DIR)/bin/activate
    pytest --html=report.html --self-contained-html
  displayName: 'Run Pytest with HTML report'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'report.html'
    artifactName: 'TestReport'
    publishLocation: 'Container'
  displayName: 'Publish HTML Report as Artifact'